services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=prod
      - PHX_HOST=${PHX_HOST}
      - DATA_ROOT=/data
      - ETHUI_STACKS_ENABLE_AUTH=1
      - ETHUI_STACKS_SAAS=1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - JWT_SECRET=${JWT_SECRET}
      - MAILER_SMTP=${MAILER_SMTP}
      - MAILER_SMTP_PORT=${MAILER_SMTP_PORT}
      - MAILER_SMTP_USERNAME=${MAILER_SMTP_USERNAME}
      - MAILER_SMTP_PASSWORD=${MAILER_SMTP_PASSWORD}
    volumes:
      - ./server/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ethui-stacks.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.stacks2.ethui.dev`)"
      - "traefik.http.routers.ethui-stacks.entrypoints=web"
      - "traefik.http.services.ethui-stacks.loadbalancer.server.port=4000"
    # depends_on:
    #   - postgres

  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: ethui_dev
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  data:
  # postgres_data:

networks:
  stacks:
    name: ethui-stacks
