import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ethui, EthuiWeb.Endpoint, server: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Ethui.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Pool + pool_size are set in runtime.exs (the default DBConnection pool, not the
# test SQL sandbox). :immediate transactions are recommended for SQLite web apps.
config :ethui, Ethui.Repo, default_transaction_mode: :immediate
