import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ethui, EthuiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Ethui.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :ethui, Ethui.Repo,
  default_transaction_mode: :immediate,
  pool: Ecto.Adapters.SQL.Sandbox,
  pool_size: System.schedulers_online() * 2

system_config_root =
  case :os.type() do
    {:unix, :darwin} -> Path.join(System.user_home!(), "Library/Application Support")
    _ -> System.get_env("XDG_CONFIG_HOME") || Path.join(System.user_home!(), ".config")
  end

config_root = Path.join(system_config_root, "ethui", "stacks")

config :ethui,
       Ethui.Repo,
       database: Path.join(config_root, "stacks.db")

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :ethui, Ethui.Stacks,
  data_dir_root: Path.join(config_root, "stacks"),
  pg_data_dir: Path.join(config_root, "pg"),
  ipfs_data_dir: Path.join(config_root, "ipfs"),
  chain_id_prefix: 0x00EE
