name: deploy stacks.ethui.dev

on:
  push:
    branches:
      - main
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    env:
      MIX_ENV: prod

    steps:
    - uses: actions/checkout@v3

    - uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.3'
        otp-version: 'OTP-27'

    - run: mix deps.get
    - run: mix compile
    - run: mix release

    - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1, hardcoded hash for security
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_DEPLOY_KEY }}

    - run: ssh-keyscan ${{ vars.DIGITALOCEAN_HOST }} >> ~/.ssh/known_hosts

    - name: Create deploy dir
      run: ssh ${{ vars.DIGITALOCEAN_USER }}@${{ vars.DIGITALOCEAN_HOST }} 'mkdir -p stacks.ethui.dev'

    - name: Upload
      run: |
        rsync \
          -az \
          --delete \
          _build/prod/rel/ethui/ \
          ${{ vars.DIGITALOCEAN_USER }}@${{ vars.DIGITALOCEAN_HOST }}:${{ vars.DEPLOY_PATH }}

    - name: Restart app
      run: |
        bin=${{ vars.DEPLOY_PATH }}/bin/ethui
        ssh ${{ vars.DIGITALOCEAN_USER }}@${{ vars.DIGITALOCEAN_HOST }} bash <<EOF
          cd stacks.ethui.dev
          source env.sh
          \$bin eval "Ethui.Release.create()"
          \$bin eval "Ethui.Release.migrate()"
          \$bin restart
        EOF

