name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    env:
      USER: postgres
      PGPASSWORD: postgres
      PGHOSTNAME: postgres
      PGDATABASE_TEST: postgres

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v4

    - uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.3'
        otp-version: 'OTP-27'

    - uses: foundry-rs/foundry-toolchain@v1

    - uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - run: mix deps.get
    - run: mix credo
    - run: mix test
